# Generated by Django 4.2.16 on 2024-11-19 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_savingproducts_savingoptions'),
    ]

    operations = [
        migrations.CreateModel(
            name='MortgageProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField(unique=True)),
                ('kor_co_nm', models.TextField()),
                ('fin_prdt_nm', models.TextField()),
                ('join_way', models.TextField()),
                ('loan_inci_expn', models.TextField()),
                ('erly_rpay_fee', models.TextField()),
                ('dly_rate', models.TextField()),
                ('loan_lmt', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MortgageOtions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_prdt_cd', models.TextField()),
                ('mrtg_type', models.TextField()),
                ('mrtg_type_nm', models.TextField()),
                ('rpay_type', models.TextField()),
                ('rpay_type_nm', models.TextField()),
                ('lend_rate_type', models.TextField()),
                ('lend_rate_type_nm', models.TextField()),
                ('lend_rate_min', models.FloatField()),
                ('lend_rate_max', models.FloatField()),
                ('lend_rate_avg', models.FloatField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.mortgageproducts')),
            ],
        ),
    ]
