# Generated by Django 4.2.16 on 2024-11-18 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_annual_income_user_assets_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_social_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='social_provider',
        ),
    ]
