# Generated by Django 4.2.16 on 2024-11-21 01:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_mortgageproducts_mortgageotions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('DEPOSIT', '예금'), ('SAVING', '적금'), ('MORTGAGE', '주택담보대출')], max_length=10)),
                ('confidence_score', models.FloatField()),
                ('rank', models.IntegerField()),
                ('recommendation_type', models.CharField(choices=[('RULE_BASED', '규칙 기반 추천'), ('ML_BASED', '머신러닝 기반 추천'), ('HIGH_RATE', '높은 금리형'), ('STABLE', '안정 추구형'), ('BALANCED', '균형형'), ('CUSTOM', '맞춤형')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deposit_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.depositproducts')),
                ('mortgage_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.mortgageproducts')),
                ('saving_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.savingproducts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['user', 'product_type', 'recommendation_type'], name='recommend_p_user_id_1304ba_idx')],
            },
        ),
    ]
